### ISSUE TITLE
Adding PostgreSQL 

### ISSUE THREAD

**Issue by marclar** [cbumgard/nodejs-vagrant#1]
Hi, Chris -- thanks for such a helpful vm :)

What's the best way to add Postgres support to this box? I added a `/sh/postgres.sh` file with these commands:

```
#!/bin/bash
apt-get update
apt-get install -y postgresql postgresql-contrib
```

It _seems_ like this should work but I'm a little confused about how to start the server when the vm boots and make it accessible to the guest machine.

Are you doing something similar for the mongo and redis servers?

**Comment by granthbr** [comment]
@marclar take a look at the sh folder. Chris is doing all of the vagrant provisioning via scripts called form that folder. To add Postgres just create a simple install script in that folder and either run do vagrant up --provision or, if the vagrant box is running, vagrant provision.

**Comment by marclar** [comment]
Thank you, @granthbr -- I see that and I added a `postgres.sh` file that I'm calling from `/sh/provision.sh`.

Finally got it working after a couple of confusing things (left here in case someone else comes along):
1. I wrote the `postgres.sh` file on Windows. Bad idea b/c of line endings, so I replaced it with [this file](https://raw.githubusercontent.com/nicferrier/pgdevbox/master/make/blank-box-init)
2. Surprisingly, it seems that a bunch of these scripts (but not all) suffered from this problem. Just replaced:
   - `/sh/github.sh`
   - `/sh/heroku.sh`
   - `/sh/redis.sh`
   - `/sh/travis.sh`
   - `/sh/vim.sh`
3. Had to edit `/sh/postgres.sh` to grant access to my host machine. Changed line 13 to `echo "host    all   all   192.168.33.1/24  trust" | sudo tee -a /etc/postgresql/9.3/main/pg_hba.conf`, though this might need to be changed if that IP changes.

Also, it seems that you have to manually remove `/etc/vagrant-provisioned` in order for the `vagrant provision` command to do anything b/c of the if statement at the beginning of `/sh/provision.sh`.
